"""user_data

Revision ID: c4e420a43bb8
Revises: 43d54f5914c9
Create Date: 2024-12-11 23:10:18.976372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4e420a43bb8'
down_revision = '43d54f5914c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('experience', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('disability', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('modified_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('modified_at')
        batch_op.drop_column('city')
        batch_op.drop_column('disability')
        batch_op.drop_column('experience')
        batch_op.drop_column('age')

    # ### end Alembic commands ###
